FROM golang:1.13.3

RUN curl -o /usr/local/bin/air https://raw.githubusercontent.com/cosmtrek/air/master/bin/linux/air && chmod +x /usr/local/bin/air

RUN mkdir /app
WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/air"]
